- uses: yukiarrr/ios-build-action@v1.12.0
  with:
    project-path: HiAnime.xcodeproj
    p12-base64: ${{ secrets.P12_BASE64 }}
    mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
    code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
    workspace-path: HiAnime.xcworkspace # optional
